export const API_BASE_URL = (
  process.env.REACT_APP_API_BASE_URL || 'https://oracleapex.com/ords/iagami_ops'
).replace(/\/$/, '');

export const API_ENDPOINTS = Object.freeze({
  DASHBOARD: '/customers/card_dashboard',
  EXECUTIVE_DASHBOARD_SUMMARY: '/reports/executive-dashboard-summary',
  EXECUTIVE_DASHBOARD_OPEN_DEMANDS: '/reports/executive-dashboard-open-demands',
  EXECUTIVE_DASHBOARD_ANALYSIS: '/reports/executive-dashboard-analysis',
  EXECUTIVE_DASHBOARD_DEMAND_AGEING_DETAILS: '/reports/executive-dashboard-demand-ageing-details',
  EXECUTIVE_DASHBOARD_TA: '/reports/executive-dashboard-ta',
  CUSTOMERS: '/customers/dashboard',
  LOVS_BASE: '/lovs/',
  ADD_CUSTOMER: '/addcustomers/addcustomer',
  UPDATE_CUSTOMER: '/addcustomers/updatecustomer',
  CUSTOMER_DETAILS: '/customers_details/details/',
  ADD_CONTACT: '/contacts_api/add',
  UPDATE_CONTACT: '/contacts_api/update',
  DELETE_CONTACT: '/contacts_api/delete',
  ADD_DEMAND: '/demands_api/add',
  UPDATE_DEMAND: '/demands_api/update',
  DEMAND_EXTRACT: '/demands_api/extract',
  DEMAND_UPLOAD: '/demands_api/upload',
  DEMAND_DOWNLOAD: '/demands_api/download',
  AI_PROMPT: '/ai/prompts',
  LOGIN: '/auth/login',
  ADD_PROFILE: '/addprofile/add',
  UPDATE_PROFILE: '/addprofile/update',
  DELETE_PROFILE: '/addprofile/delete',
  DEMAND_DETAILS: '/demands_api/details',
  PROFILE_UPLOAD: '/addprofile/upload',
  PROFILE_VIEW: '/addprofile/view-profile',
  PROFILE_ANALYZE: '/addprofile/analyze',
  PROFILE_STATUS_DB_DATA: '/profile-status/db-data',
  PROFILE_STATUS_LIST: '/profile-status/list',
  PROFILE_STATUS_UPDATE: '/profile-status/update',
  PROFILE_LOG: '/addprofile/profile-log',
  DEMAND_REPORT_CUSTOMERS: '/lovs/customers',
  DEMAND_REPORT: '/reports/demandreports',
  PROFILE_REPORT: '/reports/profilereport',
  VENDOR_REPORT: '/reports/vendorreport',
  ONBOARDED_REPORT: '/reports/onboardedreport',
  ONBOARDED_FAILED_REPORT: '/reports/onboardedfailedreport',
  CUSTOMER_REJECTED_REPORT: '/reports/customerrejectedreport',
  VENDOR_MASTER_LIST: '/getvendors/vendorlist',
  ADD_VENDOR: '/addvendors/vendor',
  DOWNLOAD_PROFILE: '/downloadprofile/profile',
  SEND_VENDOR_EMAIL: '/vendor-email/send',
  RESET_PASSWORD: '/ats/users/ats_users',
});

export const LOV_ENDPOINTS = Object.freeze({
  INDUSTRIES: `${API_ENDPOINTS.LOVS_BASE}industries`,
  TYPES: `${API_ENDPOINTS.LOVS_BASE}types`,
  ENGAGEMENT_TYPES: `${API_ENDPOINTS.LOVS_BASE}engagement-types`,
  EXECUTIVE_DASHBOARD_YEARS: `${API_ENDPOINTS.LOVS_BASE}executive-dashboard-years`,
  COUNTRIES: `${API_ENDPOINTS.LOVS_BASE}countries`,
  PROFILE_STATUSES: `${API_ENDPOINTS.LOVS_BASE}profile-statuses`,
  DEMAND_TYPES: `${API_ENDPOINTS.LOVS_BASE}demand-types`,
  JOB_TYPES: `${API_ENDPOINTS.LOVS_BASE}job-types`,
  WORK_MODES: `${API_ENDPOINTS.LOVS_BASE}work-modes`,
  DECISION_STATUSES: `${API_ENDPOINTS.LOVS_BASE}decision-statuses`,
  CURRENCIES: `${API_ENDPOINTS.LOVS_BASE}currencies`,
  PROFILE_AVAILABILITY: `${API_ENDPOINTS.LOVS_BASE}profile-availability`,
  TAX_TERMS: `${API_ENDPOINTS.LOVS_BASE}tax-terms`,
  VENDORS: `${API_ENDPOINTS.LOVS_BASE}vendors`,
  CUSTOMERS: API_ENDPOINTS.DEMAND_REPORT_CUSTOMERS,
});
